# Generated by Django 5.0.6 on 2024-06-09 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_max_attendees_event_attendees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='timestamp',
            new_name='rsvp_date',
        ),
    ]
