# Generated by Django 5.0.6 on 2024-06-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
