# Generated by Django 5.0.6 on 2024-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_created_by_remove_event_max_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
